### PR TITLE
feat: enhance the demo with syslog telemetries

### PR DESCRIPTION
**Pull request by Kevin222004**
part of #5 

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/syslog

### CODE REVIEW

**Comment by Kevin222004** [comment]
@glimchb can you help me add this syslog telemetry I am trying to forward the message using TCP and tried multiple ways but not work, I have read many things but have not been able to fix this. I have also tried to use UDP but won't work.

**Comment by glimchb** [comment]
@Kevin222004 please rebase to resolve conflicts, thank you

**Comment by Kevin222004** [comment]
@glimchb I will update this pr by tommorow

**Comment by Kevin222004** [comment]
@glimchb can you please review now and guide me what am I missing here.

**Comment by glimchb** [comment]
from CI log, when you click on failed job above, you can see:
```
2024-07-04T12:17:44.1641334Z [32;1mtelegraf_1           |[0m 2024-07-04T12:17:39Z E! [telegraf] Error running agent: starting input inputs.syslog: listen tcp 172.18.0.4:6514: bind: cannot assign requested address
```

**Review by glimchb — CHANGES_REQUESTED** [review]
ci failed

**Comment by Kevin222004** [comment]
I will fix it.

**Comment by Kevin222004** [comment]
@glimchb will it be fine if I create my own image and use it here. I am still unsure why data is not collected by telegraf from rsyslog image. I can use Ubuntu as base image and do the setup of rsyslog on that to gather data and serve it, I believe it will work .

**Pull request closed without merging**
